spring:
  application:
    name: actios-backend

  datasource:
    url: jdbc:mysql://localhost:3306/actiosdb
    username: root
    password: Flr280906@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true